module.exports = {
    'SERVER_ERROR': 'SERVER_ERROR',
    'NOT_ENOUGH_COIN': 'NOT_ENOUGH_COIN',
    'INVALID_PASSWORD': 'INVALID_PASSWORD',
    'INVALID_KEYSTORE': 'INVALID_KEYSTORE',
    'INVALID_PRIVATE_KEY': 'INVALID_PRIVATE_KEY',
};
