const ERROR_TYPES = {
  // Requesting
  REQUEST_FAILED: 'REQUEST_FAILED',

  // Validation
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  INVALID_LENGTH: 'INVALID_LENGTH',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_PRIVATE_KEY: 'INVALID_PRIVATE_KEY',
  INVALID_MNEMONIC: 'INVALID_MNEMONIC',
  INVALID_KEYSTORE: 'INVALID_KEYSTORE',
  INVALID_WALLET_ADDRESS: 'INVALID_WALLET_ADDRESS',
  PASSWORD_NOT_MATCH: 'PASSWORD_NOT_MATCH',
  NOT_ENOUGH_FUNDS: 'NOT_ENOUGH_FUNDS',

  // Transaction
  INVALID_TRANSACTION: 'INVALID_TRANSACTION',

  // User password
  INVALID_PASSWORD: 'INVALID_PASSWORD',
};


export default ERROR_TYPES;
